// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqpmhnhmexookmxxqcjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxcG1obmhtZXhvb2tteHhxY2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDU2OTMsImV4cCI6MjA3NDE4MTY5M30.tIyDcWrqjf76T1w-Zh6FFuCUXX4kn-uDgoMrBwwrFm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});